version: 2

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - npm-cache-{{ checksum "package-lock.json" }}

  persist_cache: &persist_cache
    save_cache:
      name: Save node modules cache
      key: npm-cache-{{ checksum "package-lock.json" }}
      paths:
        - ~/.cache
        - ../.npm

  test_env: &test_env
    TZ: 'UTC'
    NODE_ENV: 'circleci'
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: ''
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

jobs:
  lint:
    docker:
      - image: circleci/node:11.8.0
    environment:
      NODE_ENV: circleci
    steps:
      - checkout
      - <<: *restore_cache
      - run: npm ci --ignore-scripts
      - <<: *persist_cache
      - run: npm run lint
  prettier:
    docker:
      - image: circleci/node:11.8.0
    environment:
      NODE_ENV: circleci
    steps:
      - checkout
      - <<: *restore_cache
      - run: npm ci --ignore-scripts
      - <<: *persist_cache
      - run: npm run prettier:check
  test-bdd:
    docker:
      - image: circleci/node:11.8.0
      - image: circleci/postgres:9.6.8-alpine-postgis-ram
    environment:
      - <<: *test_env
    steps:
      - checkout
      - <<: *restore_cache
      - run: npm ci
      - <<: *persist_cache
      - run: npm run test:bdd:dev
  test-unit:
    docker:
      - image: circleci/node:11.8.0
      - image: circleci/postgres:9.6.8-alpine-postgis-ram
      - image: circleci/redis
      - image: memcached
    environment:
      - <<: *test_env
    steps:
      - checkout
      - <<: *restore_cache
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: npm ci
      - <<: *persist_cache
      - run: npm run test:unit
      - run: npm run coverage
      - store_test_results:
          path: /tmp/circleci-test-results

workflows:
  version: 2
  main:
    jobs:
      - lint
      - prettier
      - test-bdd
      - test-unit:
          filters:
            branches:
              ignore:
                - test-server
                - staging
                - production
